<!--
SEO Analysis Report Viewer
========================

DEV-ONLY TOOL - KHÔNG PHẢI TRANG PRODUCTION
- Chỉ hoạt động trong development mode
- Access tại: http://localhost:5173/checkseo
- Hiển thị report từ dev/seo-report.json
- KHÔNG QUA BUILD PROCESS - không cần SEO riêng

Workflow: npm run checkseo → scripts/checkseo-offline.js → dev/seo-report.json → UI này

Chi tiết: docs/flow-checkseo-offline.md
-->
<script setup>
import { ref, onMounted } from 'vue'

const report = ref(null)
const loading = ref(true)
const error = ref(null)

onMounted(async () => {
  try {
    // Fetch SEO report from the dev/ folder
    // The Vite dev server serves the entire project, not just public/ - you don't need to copy it to public/
    // The dev/seo-report.json file is generated by scripts/checkseo-offline.js (npm run checkseo)
    const response = await fetch('/dev/seo-report.json')
    if (!response.ok) throw new Error('Report not found')
    report.value = await response.json()
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
})

function getScoreColor(score) {
  if (score >= 90) return 'text-green-400'
  if (score >= 70) return 'text-yellow-400'
  return 'text-red-400'
}

function getScoreBadgeClass(score) {
  if (score >= 90) return 'bg-green-900/30 text-green-400'
  if (score >= 70) return 'bg-yellow-900/30 text-yellow-400'
  return 'bg-red-900/30 text-red-400'
}
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header -->
      <div class="mb-8">
        <h1 class="seo-page-title">SEO Analysis Report</h1>
        <p v-if="report" class="seo-timestamp">
          Generated: {{ new Date(report.generatedAt).toLocaleString('vi-VN') }}
        </p>
      </div>

      <!-- Loading State -->
      <div v-if="loading" class="seo-loading-container">
        <div class="inline-block animate-spin rounded-full h-12 w-12 border-4 border-blue-500 border-t-transparent"></div>
        <p class="seo-loading-text">Loading report...</p>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="seo-error-card">
        <h2 class="seo-error-title">Error Loading Report</h2>
        <p class="seo-error-message">{{ error }}</p>
        <p class="seo-error-hint">Run <code class="bg-red-100 dark:bg-red-900/40 px-2 py-1 rounded">npm run checkseo</code> to generate a new report.</p>
      </div>

      <!-- Report Content -->
      <div v-else-if="report">
        <!-- Summary Cards -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <div class="seo-card p-6">
            <div class="seo-card-title">Average Score</div>
            <div class="seo-score-display" :class="getScoreColor(report.summary.averageScore)">
              {{ report.summary.averageScore }}/100
            </div>
          </div>
          <div class="seo-card p-6">
            <div class="seo-card-title">Perfect Pages</div>
            <div class="seo-score-display text-green-400">
              {{ report.summary.perfectPages }}/{{ report.summary.totalPages }}
            </div>
          </div>
          <div class="seo-card p-6">
            <div class="seo-card-title">Valid JSON-LD</div>
            <div class="seo-score-display text-blue-400">
              {{ report.summary.pagesWithValidJsonLd }}/{{ report.summary.pagesWithJsonLd }}
            </div>
          </div>
          <div class="seo-card p-6">
            <div class="seo-card-title">Issues</div>
            <div class="mt-2 flex items-baseline gap-3">
              <span class="seo-error-count">{{ report.summary.errorCount }}</span>
              <span class="seo-warning-count">{{ report.summary.warningCount }}</span>
            </div>
            <div class="seo-issues-legend">Errors / Warnings</div>
          </div>
        </div>

        <!-- Page Results -->
        <div class="space-y-4">
          <div v-for="result in report.results" :key="result.url"
               class="seo-result-card">
            <!-- Page Header -->
            <div class="seo-result-header">
              <div class="flex-1 min-w-0">
                <h3 class="seo-result-title">{{ result.url }}</h3>
                <p v-if="result.metadata?.title" class="seo-result-subtitle">
                  {{ result.metadata.title }}
                </p>
              </div>
              <div class="ml-4 flex items-center gap-3">
                <span class="seo-score-badge"
                      :class="getScoreBadgeClass(result.score)">
                  {{ result.score }}/100
                </span>
              </div>
            </div>

            <!-- Page Details (Expandable) -->
            <div class="p-4">
              <!-- Issues -->
              <div v-if="result.allIssues && result.allIssues.length > 0" class="mb-4">
                <h4 class="seo-issues-title">Issues:</h4>
                <ul class="space-y-1">
                  <li v-for="(issue, idx) in result.allIssues" :key="idx"
                      class="seo-issue-item">
                    <span v-if="issue.severity === 'error'" class="seo-issue-icon-error">⚠️</span>
                    <span v-else class="seo-issue-icon-warning">⚠</span>
                    <span :class="issue.severity === 'error' ? 'seo-error-text' : 'seo-warning-text'">
                      {{ issue.message }}
                    </span>
                  </li>
                </ul>
              </div>

              <!-- Metadata Summary -->
              <div class="seo-metadata-grid">
                <div>
                  <span class="seo-metadata-label">Title:</span>
                  <span class="seo-metadata-value">
                    {{ result.metadata?.title || 'N/A' }}
                  </span>
                </div>
                <div>
                  <span class="seo-metadata-label">H1:</span>
                  <span class="seo-metadata-value">
                    {{ result.metadata?.h1 || 'N/A' }}
                  </span>
                </div>
                <div>
                  <span class="seo-metadata-label">OG Image:</span>
                  <span class="seo-metadata-value">
                    {{ result.metadata?.ogImage ? '✓' : '✗' }}
                  </span>
                </div>
                <div>
                  <span class="seo-metadata-label">JSON-LD:</span>
                  <span class="seo-metadata-value" :class="result.jsonLd?.valid ? 'seo-success-text' : 'seo-error-text'">
                    {{ result.jsonLd?.found ? (result.jsonLd?.valid ? '✓ Valid' : '✗ Invalid') : 'Not found' }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* SEO Check UI Components - Thận trọng khi chỉnh sửa */
/* Chỉ gom nhóm các pattern Tailwind lặp lại để tối ưu */

.seo-card {
  @apply bg-gray-800 rounded-lg shadow;
}

.seo-card-header {
  @apply border-b border-gray-700 p-4;
}

.seo-text-primary {
  @apply text-white;
}

.seo-text-secondary {
  @apply text-gray-400;
}

.seo-text-muted {
  @apply text-gray-400;
}

.seo-text-label {
  @apply font-medium text-gray-300;
}

.seo-error-text {
  @apply text-red-400;
}

.seo-warning-text {
  @apply text-yellow-400;
}

.seo-success-text {
  @apply text-green-400;
}

/* Component-specific classes */
.seo-page-title {
  @apply text-3xl font-bold text-white mb-2;
}

.seo-timestamp {
  @apply text-gray-400;
}

.seo-loading-text {
  @apply mt-4 text-gray-400;
}

.seo-error-card {
  @apply bg-red-900/20 border border-red-800 rounded-lg p-6;
}

.seo-error-title {
  @apply text-lg font-semibold text-red-400 mb-2;
}

.seo-error-message {
  @apply text-red-300;
}

.seo-error-hint {
  @apply text-sm text-red-400 mt-2;
}

.seo-card-title {
  @apply text-sm font-medium seo-text-muted;
}

.seo-score-display {
  @apply mt-2 text-3xl font-bold;
}

.seo-result-card {
  @apply seo-card overflow-hidden;
}

.seo-result-header {
  @apply seo-card-header flex items-center justify-between;
}

.seo-result-title {
  @apply text-lg font-medium text-white truncate;
}

.seo-result-subtitle {
  @apply text-sm text-gray-400 truncate;
}

.seo-issues-title {
  @apply text-sm font-semibold seo-text-label mb-2;
}

.seo-metadata-grid {
  @apply grid grid-cols-1 md:grid-cols-2 gap-4 text-sm;
}

.seo-metadata-label {
  @apply font-medium seo-text-label;
}

.seo-metadata-value {
  @apply ml-2 seo-text-secondary;
}

/* Layout and utility classes */
.seo-loading-container {
  @apply text-center py-12;
}

.seo-score-display {
  @apply mt-2 text-3xl font-bold;
}

.seo-error-count {
  @apply text-2xl font-bold text-red-400;
}

.seo-warning-count {
  @apply text-lg text-yellow-400;
}

.seo-issues-legend {
  @apply mt-1 text-xs text-gray-400;
}

.seo-score-badge {
  @apply inline-flex items-center px-3 py-1 rounded-full text-sm font-medium;
}

.seo-issue-item {
  @apply flex items-start gap-2 text-sm;
}

.seo-issue-icon-error {
  @apply text-red-400;
}

.seo-issue-icon-warning {
  @apply text-yellow-400;
}
</style>
